dist: xenial
sudo: required
language: cpp
compiler: clang
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script: curl -T hello_world-0.0-$TRAVIS_BUILD_NUMBER-Linux.deb -kotovdv:$BINTRAY_API_KEY "https://api.bintray.com/content/kotovdv/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/hello_world-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"